### PR TITLE
Fix #69 Add login failure lockout support

### LINKED ISSUE #69: Lock out accounts after 100 consecutive failed login attempts
See 800 63B 5.2.2 (https://pages.nist.gov/800-63-3/sp800-63b.html#sec5).

Users will have to contact support to have their account unlocked.

### PR DESCRIPTION
**Pull request by schellj**
Locks out users from logging in after a configurable number of login failures.

The implementation uses a new `realm_owner_t` `login_failure_count` and implicitly determines if a realm owner is locked based on that count. An alternate implementation could also employ an explicit `login_locked` field. I tried out both implementations and the former is cleaner and requires less logic and state management, though I would be fine with the latter if there were strong feelings about maintaining explicit state.

### CODE REVIEW

**Review by robnagler — CHANGES_REQUESTED** [review]
I think for this type of problem, we may want to be able to audit login attempts. You could check how many failed logins we get. Indeed, we might want to have a record of all logins so we can provide feedback to users more easily (you tried to login from this IP on this date), just like other sites do. 

Adding this feature to RealmOwner seems problematic, because it will not be used in all sites, just bivio.com. Once an account is locked, we can simply reset the password, and force them to enter a new password via forgot password. This will validate their email is still valid (really all we have to validate anyway).

We can then count login failures from the last successful login to determine if their account should be locked. This puts a heavier "cost" on login failures, but that's a good thing in any even (slowing down attempts).

I did not review the code specifically.

**Comment by schellj** [comment]
> Adding this feature to RealmOwner seems problematic, because it will not be used in all sites, just bivio.com.

Why just bivio.com? I thought the idea was that this, along with the password changes, would be good to do for all sites.

**Comment by robnagler** [comment]
That makes sense. Probably better to just do it for all sites. Still, I think putting it in RealmOwner does not provide enough data for us to determine why/when an account was locked out.

**Comment by robnagler** [comment]
You can't actually limit attempts. What you can do is limit responses. This gets tricky with someone determined to make multiple attempts.  Your idea will help with that with the exception that we lose the log of the other attempts, because there will be a rollback. This is probably fine, and we should avoid logging too much (the sql exception should be caught and the reply should just be "error" or something). 

It's unlikely a human will attempt twice in one second except for double click. We could add some javascript to avoid this problem, but let's see if it occurs first.

Let's avoid overloading our db by recording the http_user_agent and referer. They are worthless if there's a real attack (iwc they'll be spoofed), which is the only case that would get to 100 failed attempts.

Change the success/lockout to login_attempt_state. They are mutually exclusive states. There are three states: success, failure, lockout (implicitly failure).

**Comment by schellj** [comment]
So, you think the benefits of the realm_id/date primary key are worth the testing pain? There's going to have to be some changes to allow for a fair number of tests (especially acceptance tests) to pass without tripping constraint errors.

> You can't actually limit attempts. What you can do is limit responses. This gets tricky with someone determined to make multiple attempts. Your idea will help with that with the exception that we lose the log of the other attempts, because there will be a rollback. This is probably fine, and we should avoid logging too much (the sql exception should be caught and the reply should just be "error" or something).

The entire reply should just be `error`? Is there a way to do that similar to a die? Otherwise, could do a `throw_quietly` to limit the log spam.

> Let's avoid overloading our db by recording the http_user_agent and referer. They are worthless if there's a real attack (iwc they'll be spoofed), which is the only case that would get to 100 failed attempts.
> 
> Change the success/lockout to login_attempt_state. They are mutually exclusive states. There are three states: success, failure, lockout (implicitly failure).

Good points.

**Comment by robnagler** [comment]
> So, you think the benefits of the realm_id/date primary key are worth the testing pain? There's going to have to be some changes to allow for a fair number of tests (especially acceptance tests) to pass without tripping constraint errors.

Are you thinking that we will have more than one login attempt a second that is committed? I don't think unit tests use login form to login. That's the only place a login attempt should be used, not in set_user. Acceptance tests probably don't make more than one login attempt a second, because they do things correctly. 

An alternative is that we could have a separate login_success_t with a login_success_id that's unique.

> The entire reply should just be error? Is there a way to do that similar to a die? Otherwise, could do a throw_quietly to limit the log spam.

Yes, you don't give information to the hacker. Real users are not going to try multiple failed logins within a second. It's just not possible. And, we can make sure it doesn't happen in the browser by limiting failed attempts there. All you have to do is gray out the login button, set a timer, and ungray it after a second has passed.

**Comment by schellj** [comment]
> Are you thinking that we will have more than one login attempt a second that is committed? I don't think unit tests use login form to login. That's the only place a login attempt should be used, not in set_user. Acceptance tests probably don't make more than one login attempt a second, because they do things correctly.

I haven't looked at them in detail, but 10 of the acceptance tests failed when I ran the suite last night with the realm_id/date primary key. I can run them all again with my current code, but I think at least some of them are going to be flaky unless `set_test_now`s or `sleep`s are employed.

I don't know that this gains anything of substance if the difference is that an attacker gets to the 100 failure lockout in 10s vs 100s and causes testing to be more flaky.

> An alternative is that we could have a separate login_success_t with a login_success_id that's unique.

You mean `login_attempt_t` with `login_attempt_id`? I had it coded that way at one point as well.

If you mean a second new table `login_success_t`, then I'm not sure I follow.

> > The entire reply should just be error? Is there a way to do that similar to a die? Otherwise, could do a throw_quietly to limit the log spam.
> 
> Yes, you don't give information to the hacker. Real users are not going to try multiple failed logins within a second. It's just not possible. And, we can make sure it doesn't happen in the browser by limiting failed attempts there. All you have to do is gray out the login button, set a timer, and ungray it after a second has passed.

Yeah, I understand that this doesn't affect real users. How is it giving the hacker less new information if you send back just `error`, vs a usual server error? The latter doesn't tell them why there was a server error and the former seems more suspicious as it's different than a typical error.

**Comment by robnagler** [comment]
> If you mean a second new table login_success_t, then I'm not sure I follow.

If you have two tables (failures and successes), then all the tests will run, because the vast majority of the tests are about successes, not failures. There's no logic in inhibiting multiple successful logins so success can have a sequence as a primary key. 

For the tests that are testing login failures, they will have to set time and manage things.

By separating the two tables, it makes it easier to write the code, because a successful login has a different path entirely and so a different record is created. You can then say "when is the most successful login" by loading most recent on that table. 

>  How is it giving the hacker less new information if you send back just error, vs a usual server error?

What I mean was that you don't want it to get to a server error case, because a DDOS attack would flood the logs. You can return a 500 or whatever in the case of too frequent attempts, but write the code so that the log doesn't get cluttered.

In thinking about this more, we don't care about the speed of attempts. Rather, we just care about the maximum attempts. It's hard to slow down a determined hacker. On entry, you have to check for the locked account anyway so simply have a primary key as a sequence in the failed case. 

This speaks to having a single table again, but just adding a primary id that's a sequence so you don't get collisions.

**Comment by schellj** [comment]
@robnagler Do you mind taking a look at the latest changes here?

File: Biz/Model/UserLoginBaseForm.pm [hunk 1]
```diff
@@ -113,6 +125,48 @@ sub validate {
...
+    if ($errors->{'login'} && $errors->{'login'}->eq_locked_out) {
+        b_warn('locked out owner=', $owner);
+        # Return non-specific errror so potential attacker doesn't glean additional information
+        return {
+            method => 'server_redirect',
+            task_id => 'DEFAULT_ERROR_REDIRECT',
+            query => undef,
+        };
+    }
+    # Have to do this after form processing as the transaction gets rolled back upon form errors
```
Comment (robnagler) [inline Biz/Model/UserLoginBaseForm.pm:144]: The comment might be better this way: We do not fall through, because form_errors will rollback, clearing the LoginAttempt. The server_redirect ensures the lockout message is shown to the user.

File: UI/FacadeBase.pm [hunk 2]
```diff
@@ -2118,6 +2118,24 @@ password.
...
+vs_site_name(); Support
+EOF
+                    ],
+                    user_lockout_mail => [
+                        to => q{Mailbox(['Model.UserLoginForm', 'Email.email']);},
+                        subject => 'vs_site_name(); Account Locked',
+                        body => <<'EOF',
+We have locked your account due to a large number of failed login attempts. This is done to prevent
+potential attackers from being able to guess your password. To regain access to your account, follow
+link below or use the forgot password form.
```
Comment (robnagler) [inline UI/FacadeBase.pm:2131]: For a lockout, they must contact support.

File: Biz/Model/UserLoginBaseForm.pm [hunk 3]
```diff
@@ -113,6 +125,48 @@ sub validate {
...
+    if (
+        $errors->{'RealmOwner.password'}
+        && _record_login_attempt($self, $owner, 0)->get('login_attempt_state')->eq_lockout
+    ) {
+        b_warn('failed login attempt triggered lock out owner=', $owner);
+        $self->req->with_realm($owner, sub {
+            $self->internal_put_field(
+                'Email.email' => $self->new_other('Email')->load({
```
Comment (robnagler) [inline Biz/Model/UserLoginBaseForm.pm:152]: In this situation, keep this code very simple to avoid errors that might cause a rollback. The lockout mail task can then get `$owner` from this form and do the step of looking up an email. The mail task can then render the page that says the account is locked.

File: Biz/Model/UserLoginBaseForm.pm [hunk 4]
```diff
@@ -130,11 +184,26 @@ sub validate_login {
     return $realm;
 }
 
+sub _record_login_attempt {
+    my($self, $owner, $success) = @_;
+    return $self->req->with_realm($owner, sub {
```
Comment (robnagler) [inline Biz/Model/UserLoginBaseForm.pm:189]: Do not switch realms, because this is prone to error. Again, keep the code doing as little as possible once a failed login attempt has been detected. Just call create and supply realm_id, which is unauthenticated for create.

File: Biz/Model/UserLoginBaseForm.pm [hunk 5]
```diff
@@ -130,11 +184,26 @@ sub validate_login {
...
+        });
+    });
+}
+
 sub _validate {
     my($self) = @_;
     my($owner) = $self->validate_login;
     return
         if !$owner || ($self->in_error && !$owner->require_otp);
+    if ($self->req->with_realm($owner, sub {
```
Comment (robnagler) [inline Biz/Model/UserLoginBaseForm.pm:201]: Don't switch realms. This is expensive and complicated. This is a login form so we don't want to "go into" the realm until we know we have authenticated the user. In this case, you would unauth_load_last. Also this type of code is better modularized in another sub so this could would look like:

```perl
return
    unless _validate_login_attempt($self);
```

File: Biz/Model/UserPasswordForm.pm [hunk 6]
```diff
@@ -18,6 +18,7 @@ sub execute_ok {
         realm_owner => $req->get_nested(qw(auth_realm owner))
             ->update_password($self->get('new_password')),
     });
+    $self->new_other('LoginAttempt')->create({login_attempt_state => $_LAS->SUCCESS});
```
Comment (robnagler) [inline Biz/Model/UserPasswordForm.pm:21]: Do not do this. This is not a login attempt.

File: SQL/DDL.pm [hunk 7]
```diff
@@ -1028,6 +1027,21 @@ CREATE INDEX user_default_subscription_t5 ON user_default_subscription_t (
...
+--
+ALTER TABLE login_attempt_t
+  ADD CONSTRAINT login_attempt_t2
+  FOREIGN KEY (realm_id)
+  REFERENCES realm_owner_t(realm_id)
+/
+CREATE INDEX login_attempt_t3 ON login_attempt_t (
+  realm_id,
+  creation_date_time,
+  login_attempt_id
```
Comment (robnagler) [inline SQL/DDL.pm:1042]: Don't add login_attempt_id, because it complicates the index. There's already an index on that.

File: Delegate/SimpleTypeError.pm [hunk 8]
```diff
@@ -433,6 +432,10 @@ sub get_delegate_info {
         undef,
         'File names may not contain a leading dot.',
     ],
+    LOCKED_OUT => [
+        83,
+        # No description as this error is not shown to the user.
```
Comment (robnagler) [inline Delegate/SimpleTypeError.pm:437]: Description needs to come from facade because it should include a link to contact support. The default description won't be shown therefore.

File: Delegate/SimpleTypeError.pm [hunk 9]
```diff
@@ -433,6 +432,10 @@ sub get_delegate_info {
         undef,
         'File names may not contain a leading dot.',
     ],
+    LOCKED_OUT => [
```
Comment (robnagler) [inline Delegate/SimpleTypeError.pm:435]: Give the object: LOGIN_LOCKED_OUT.

File: Delegate/TaskId.pm [hunk 10]
```diff
@@ -1594,6 +1593,8 @@ sub info_user_auth {
             Action.UserLogout
             Model.UserLoginForm
             View.UserAuth->login
+            lockout_task=GENERAL_USER_LOCKOUT_MAIL
+            reset_task=USER_PASSWORD_RESET
```
Comment (robnagler) [inline Delegate/TaskId.pm:1597]: Remove reset_task.

File: Delegate/TaskId.pm [hunk 11]
```diff
@@ -1665,7 +1666,17 @@ sub info_user_auth {
...
         )],
-#97-99
+        # Redirect to non-specific errror so potential attacker doesn't glean additional information
+        [qw(
+            GENERAL_USER_LOCKOUT_MAIL
+            98
+            GENERAL
+            ANYBODY
+            View.UserAuth->user_lockout_mail
+            Action.ServerRedirect->execute_next
```
Comment (robnagler) [inline Delegate/TaskId.pm:1676]: Just render a page with a simple message "account locked".

**Review by robnagler — CHANGES_REQUESTED** [review]
I wasn't clear about the error messages. Hopefully review is self-explanatory. I didn't review the tests.

File: Biz/Model/LoginAttempt.pm [hunk 12]
```diff
@@ -0,0 +1,83 @@
...
+
+sub internal_initialize {
+    my($self) = @_;
+    return $self->merge_initialize_info($self->SUPER::internal_initialize, {
+        version => 1,
+        table_name => 'login_attempt_t',
+        as_string_fields => [qw(realm_id login_attempt_state ip_address)],
+        columns => {
+            login_attempt_id => ['PrimaryId', 'PRIMARY_KEY'],
+            $self->REALM_ID_FIELD => [$self->REALM_ID_FIELD_TYPE, 'NOT_NULL'],
```
[the remark this answers is not in the document]
Comment (schellj) [reply Biz/Model/LoginAttempt.pm:36]: Right, I had had to change the constraint when the primary key was realm_id/creation_date_time.

File: Biz/Model/LoginAttempt.pm [hunk 13]
```diff
@@ -0,0 +1,83 @@
...
+        my($it) = @_;
+        return 0
+            if $it->get('login_attempt_state')->eq_success
+            || $it->get('login_attempt_state')->eq_reset;
+        if (++$fail_count >= $_CFG->{lockout_failure_count}) {
+            $state = $_S->LOCKOUT;
+            return 0;
+        }
+        return 1;
+    }, 'creation_date_time DESC, login_attempt_id DESC');
```
[the remark this answers is not in the document]
Comment (schellj) [reply Biz/Model/LoginAttempt.pm:79]: You do because there could be multiple attempts with the same creation_date_time.

File: UI/FacadeBase.pm (hunk 2 above)
Comment (schellj) [reply UI/FacadeBase.pm:2131]: What's the reasoning for not allowing the user to unlock their account themselves?

File: Biz/Model/LoginAttempt.pm (hunk 13 above)
[the remark this answers is not in the document]
Comment (robnagler) [reply Biz/Model/LoginAttempt.pm:79]: But the order doesn't matter in this case. If there are N attempts within the same second, they all get checked. By not including this, your 

There's a very odd condition that is "safe" to code this way. If there are max_attempts -1 (or 2) failed attempts from the last previous attempt AND there was a failure(s) in that same second as the success. You'll get a miscount, but I think that's ok. There can only be so many attempts per second (from a compute availability perspective) so if we miscount and give a few more attempts, it's fine.

NOTE: you need to add an index just on realm_id.

File: UI/FacadeBase.pm (hunk 2 above)
Comment (robnagler) [reply UI/FacadeBase.pm:2131]: It makes sense to me, because that's what banks do. This is an extreme case, and we want to have some "back and forth" to verify that the person has access to the account (who is your club administrator, when did you last successfully login, etc.). I looked in NIST-63B, and there's nothing about what to do other than "Requiring the claimant to wait following a failed attempt for a period of time that increases as the account approaches its maximum allowance for consecutive failed attempts (e.g., 30 seconds up to an hour)."  That doesn't make much sense to me. The safest way to insert a significant delay is to contact support.

File: Biz/Model/LoginAttempt.pm (hunk 13 above)
[the remark this answers is not in the document]
Comment (schellj) [reply Biz/Model/LoginAttempt.pm:79]: > But the order doesn't matter in this case. If there are N attempts within the same second, they all get checked. By not including this, your

Looks like your sentence got cut off.

> There's a very odd condition that is "safe" to code this way. If there are max_attempts -1 (or 2) failed attempts from the last previous attempt AND there was a failure(s) in that same second as the success. You'll get a miscount, but I think that's ok. There can only be so many attempts per second (from a compute availability perspective) so if we miscount and give a few more attempts, it's fine.

It seems like it would make the code less clear to write to this "very odd condition" when we can just sort by both columns and ensure that the sequence is correct.

It also makes the testing harder because you have to account for the possibility of the count being off.

> NOTE: you need to add an index just on realm_id.

When are we querying for attempts without caring about the order? Or is there a reason that I'm not thinking of to have an index only on realm_id?

File: Biz/Model/UserPasswordForm.pm (hunk 6 above)
Comment (schellj) [reply Biz/Model/UserPasswordForm.pm:21]: FWIW, this was here to allow for the account to be unlocked via the reset password email. If support has to unlock the account, then yes this can be removed.

File: Util/RealmAdmin.pm [hunk 14]
```diff
@@ -237,6 +237,15 @@ sub leave_user {
     return;
 }
 
+sub reset_login {
```
[the remark this answers is not in the document]
Comment (schellj) [reply Util/RealmAdmin.pm:240]: Noted, though including password was mostly for convenience for testing. I wouldn't expect (or condone) to be giving any passwords via email.

File: Biz/Model/LoginAttempt.pm (hunk 13 above)
[the remark this answers is not in the document]
Comment (robnagler) [reply Biz/Model/LoginAttempt.pm:79]: > "By not including this, your"

Not sure what I was thinking. :)

> code less clear to write to this "very odd condition" 

This case can be ignored. It really only matters when the number of failures is very high (and really just near the max). We might lock somebody out with, say, max-2 attempts, but that's ok. Nobody is going to count this, since we don't publish the number of failures allowed (that would be silly).

> we can just sort by both columns 

This has a cost, and with a large table like this one, a big cost, I believe. The index will get large and less usable over time.

You need a few indices: (login_attempt_id), (realm_id), (realm_id, creation_date_time). If you add this final index (login_attempt_id, realm_id, creation_date_time) for sorting, I'm concerned about Postgres choosing the wrong index.

> ensure that the sequence is correct.

Sequences do not have a guaranteed time order. Testing can be ordered by faking the time.

> It also makes the testing harder because you have to account for the possibility of the count being off.

The testing can use fake times, I believe.

> When are we querying for attempts without caring about the order? Or is there a reason that I'm not thinking of to have an index only on realm_id?

realm_id needs an index, because it's a foreign key. It makes checks for deletes on the foreign table faster (otherwise it has to scan the entire table for constraint violations).

File: Util/RealmAdmin.pm (hunk 14 above)
[the remark this answers is not in the document]
Comment (robnagler) [reply Util/RealmAdmin.pm:240]: In general, the tests can be modularized (combining reset_lock and reset_password into a single test function) to avoid this without adding options to the main code. We try to avoid (and don't always succeed) modifying the main code to have special cases for testing.

File: Biz/Model/LoginAttempt.pm (hunk 13 above)
[the remark this answers is not in the document]
Comment (robnagler) [reply Biz/Model/LoginAttempt.pm:79]: And, the larger index (login_attempt_id, realm_id, creation_date_time) is going to be large (possibly as large as the table itself), because none of the values align and PG has to keep ordering.

[the remark this answers is not in the document]
Comment (schellj) [reply Biz/Model/LoginAttempt.pm:79]: > realm_id needs an index, because it's a foreign key.

Ah, MySQL creates indices for foreign keys automatically.

File: Biz/Model/UserLoginBaseForm.pm (hunk 1 above)
Comment (schellj) [reply Biz/Model/UserLoginBaseForm.pm:144]: I added this comment to point out that the login attempt can't be recorded at some earlier point, like in `validate`. Saying that we don't fall through isn't helpful to me. I understand (now) that `validate` wouldn't be the right place to record or modify data in general, but I didn't realize that before I started this PR.

Comment (robnagler) [reply Biz/Model/UserLoginBaseForm.pm:144]: OK. However you want to document is fine. I would say validate is fine enough. It's more complicated to do it any other way, because you have to catch all cases.

Comment (schellj) [reply Biz/Model/UserLoginBaseForm.pm:144]: > I would say validate is fine enough.

Do you mean recording the login attempt is fine enough in `validate`? As I say, if there are form errors, then that record would get rolled back.

Comment (robnagler) [reply Biz/Model/UserLoginBaseForm.pm:144]: The record shouldn't get rolled back when the password is incorrect. I think we might be able to avoid this by setting [stay_on_page](https://github.com/biviosoftware/perl-Bivio/blob/71d45f48cb1621d8d316c1bf04ab63b88b665821/Biz/FormModel.pm#L1033) when there are form_errors. I don't know if we use it this way in other places, but I think it makes sense to do it this way.

Comment (schellj) [reply Biz/Model/UserLoginBaseForm.pm:144]: Thanks.

**Comment by schellj** [comment]
@robnagler I believe I've addressed all of your comments from your prior review, if you could give this another look. Thanks.

File: Biz/Action/UserLockout.pm [hunk 15]
```diff
@@ -0,0 +1,17 @@
...
+package Bivio::Biz::Action::UserLockout;
+use strict;
+use Bivio::Base 'Biz.Action';
+
+my($_E) = b_use('Model.Email');
+
+sub execute_load_owner_email {
+    my(undef, $req) = @_;
+    $req->put(locked_owner_email => $_E->new($req)->unauth_load_or_die({
+        realm_id => $req->get_nested(qw(Model.UserLoginForm realm_owner realm_id)),
```
Comment (robnagler) [inline Biz/Action/UserLockout.pm:11]: FYI: `$req->req` does the same thing and is shorter.

File: Biz/Action/UserLockout.pm [hunk 16]
```diff
@@ -0,0 +1,17 @@
+# Copyright (c) 2023 bivio Software, Inc.  All rights reserved.
+package Bivio::Biz::Action::UserLockout;
+use strict;
+use Bivio::Base 'Biz.Action';
+
+my($_E) = b_use('Model.Email');
+
+sub execute_load_owner_email {
+    my(undef, $req) = @_;
+    $req->put(locked_owner_email => $_E->new($req)->unauth_load_or_die({
```
Comment (robnagler) [inline Biz/Action/UserLockout.pm:10]: I think values like this should never be put straight on the request. Rather, they should be put on `$self` and then referenced from there. This makes global name space management easier. See Action.Acknowledgement->_extract for an example (there are other suboptimal examples in there).

File: Biz/Model/LoginAttempt.pm [hunk 17]
```diff
@@ -0,0 +1,96 @@
...
+    my($state) = $values->{login_attempt_state};
+    return $state
+        if $state->eq_success || $state->eq_reset;
+    b_die('unexpected login_attempt_state=', $state)
+        unless $state->eq_failure;
+    my($fail_count) = 1;
+    _iterate($self->new_other('LoginAttempt'), $values->{realm_id}, sub {
+        my($it) = @_;
+        return 0
+            if $it->get('login_attempt_state')->eq_success
```
Comment (robnagler) [inline Biz/Model/LoginAttempt.pm:85]: `equals_by_name` might make sense here.

File: Biz/Model/RealmOwner.pm [hunk 18]
```diff
@@ -333,20 +337,25 @@ sub update_password {
     });
 }
 
-sub validate_login {
-    my($self, $login) = @_;
-    my($err) = !$self->unauth_load_by_email_id_or_name($login) ? ''
-        : $self->is_offline_user ? 'is_offline_user'
+sub validate {
```
Comment (robnagler) [inline Biz/Model/RealmOwner.pm:340]: `validate` is too short. `validate_login_for_self'? Or validate_login becomes load_and_validate_login and validate becomes validate_login, but this cascades so better to keep validate_login as API unchanged.

File: Biz/Model/UserLoginBaseForm.pm [hunk 19]
```diff
@@ -130,26 +150,59 @@ sub validate_login {
...
 
-sub _validate {
-    my($self) = @_;
-    my($owner) = $self->validate_login;
-    return
-        if !$owner || ($self->in_error && !$owner->require_otp);
+sub _password_error {
+    my($self, $owner) = @_;
+    my($pw_err);
     unless ($owner->get_field_type('password')->is_equal(
```
Comment (robnagler) [inline Biz/Model/UserLoginBaseForm.pm:156]: probably a shortcut exit would be clearer:

```perl
return undef
    if $owner->get_field_type('password')->is_equal(...)
```

File: Delegate/TaskId.pm [hunk 20]
```diff
@@ -1594,6 +1593,7 @@ sub info_user_auth {
             Action.UserLogout
             Model.UserLoginForm
             View.UserAuth->login
+            lockout_mail_task=GENERAL_USER_LOCKOUT_MAIL
```
Comment (robnagler) [inline Delegate/TaskId.pm:1596]: `GENERAL_USER_LOCKED_OUT`. It is not purely a mail task. It renders a page.

I think the names lockout and locked_out  should be merged. Either refer to a LOCKOUT or LOCKED_OUT, everywhere.

**Review by robnagler — CHANGES_REQUESTED** [review]
Looks good. A few comments.

File: Delegate/TaskId.pm (hunk 20 above)
Comment (schellj) [reply Delegate/TaskId.pm:1596]: Yeah, "lockout" is intended to be the verb and "locked out" is the adjective, but I understand how it's confusing as they are too similar sounding.

**Comment by schellj** [comment]
@robnagler Comments addressed.

**Review by robnagler — APPROVED** [review]
LGTM. I'll let you merge.
